server.port: 8090
packageRoute:
  maximumDistancePackage: 0.00006 # Aproxidamente 5 cuadras de Radio en CABA (calculado con lat,lng)
  limitDeliveryPackages: 5
w3w:
  key: 'U37MJGXM'
user:
  timezone: 'UTC'

here:
  credentials:
    key: 'VoWVNJa2znkRfel7H4L6'
    kode: 't1qCHEaT0xu_NS39nOL2MQ'

spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
  jpa:
    hibernate:
      naming:
        physical-strategy: 'com.paquery.maps.configuration.NamingStrategyDatabase'

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        exclude: '*'
      web:
        exposure:
          include: 'health,info,loggers,caches'
  endpoint:
    loggers:
      enabled: true

info:
  app: 'MS Maps'
  version: ${version}
  nombre: ${name}

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    com.paquery: DEBUG

admin:
  username: maps-admin
  password: p4ck4g3s

---
spring:
  profiles: default
  data:
    rest:
      base-path: '/'
  datasource:
    url: 'jdbc:sqlserver://localhost\master:1433'
    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    username: 'SA'
    password: 'Paquery01'
    test-on-borrow: true
    validation-query: 'SELECT 1'
    log-validation-errors: true
    max-active: 20
    initial-size: 4
    autoReconnect: true
    autoReconnectForPools: true
    is-connection-validation-required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


---
spring:
  profiles: preprod
  data:
    rest:
      base-path: '/'
  datasource:
    url: 'jdbc:sqlserver://10.84.87.3:1433;databaseName=paquery-preprod-db'
    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    username: 'paquery-preprod-db'
    password: 'qXE5nv6u4cRuVXty'
    test-on-borrow: true
    validation-query: 'SELECT 1'
    log-validation-errors: true
    max-active: 20
    initial-size: 4
    autoReconnect: true
    autoReconnectForPools: true
    is-connection-validation-required: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#hibernate:
#  hbm2ddlAuto: 'none'
#  showSql: true


---
spring:
  profiles: production
  data:
    rest:
      base-path: '/'
  datasource:
    url: 'jdbc:sqlserver://10.209.85.194:1433;databaseName=paquery-prod-db'
    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    username: 'paquery-prod-db'
    password: 'sn5eswJjN5XmALWVCJXf'
    test-on-borrow: true
    validation-query: 'SELECT 1'
    log-validation-errors: true
    max-active: 20
    initial-size: 4
    autoReconnect: true
    autoReconnectForPools: true
    is-connection-validation-required: true
hibernate:
  hbm2ddlAuto: 'none'
  showSql: false


logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    com.paquery: INFO

admin:
  username: maps-admin
  password: m@p5pqry!